#!/bin/bash
#

BB_PATH=`dirname ${BASH_SOURCE[0]}`
export PATH="$BB_PATH/bin:$PATH"
export PATH="$BB_PATH/local/bin:$PATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$BB_PATH/local/lib"

BB_LOGS_DIR="`bb | grep MAIN | awk -F: '{print $2}'`/logs"

if [ `ls $BB_LOGS_DIR/*.sh 2>/dev/null | wc -l` != "0" ]
then
  for s in $BB_LOGS_DIR/*.sh
  do
    source $s
  done
fi
